// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetConfig():Promise<app.AppConfig>;

export function GetConfigPath():Promise<string>;

export function GetHotkey():Promise<string>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetServiceState():Promise<boolean>;

export function GetStartMinimized():Promise<boolean>;

export function GetTrayNotifications():Promise<boolean>;

export function LoadConfig():Promise<void>;

export function OnShutdown():Promise<void>;

export function ResetToDefaults():Promise<void>;

export function SaveConfig(arg1:app.AppConfig):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetServiceState(arg1:boolean):Promise<void>;

export function SetStartMinimized(arg1:boolean):Promise<void>;

export function SetTrayNotifications(arg1:boolean):Promise<void>;

export function ValidateHotkey(arg1:string):Promise<void>;
