// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['app']['ConfigManager']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['app']['ConfigManager']['GetConfigPath']();
}

export function GetHotkey() {
  return window['go']['app']['ConfigManager']['GetHotkey']();
}

export function GetMinimizeToTray() {
  return window['go']['app']['ConfigManager']['GetMinimizeToTray']();
}

export function GetServiceState() {
  return window['go']['app']['ConfigManager']['GetServiceState']();
}

export function GetStartMinimized() {
  return window['go']['app']['ConfigManager']['GetStartMinimized']();
}

export function GetTrayNotifications() {
  return window['go']['app']['ConfigManager']['GetTrayNotifications']();
}

export function LoadConfig() {
  return window['go']['app']['ConfigManager']['LoadConfig']();
}

export function OnShutdown() {
  return window['go']['app']['ConfigManager']['OnShutdown']();
}

export function ResetToDefaults() {
  return window['go']['app']['ConfigManager']['ResetToDefaults']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['ConfigManager']['SaveConfig'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['app']['ConfigManager']['SetHotkey'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['app']['ConfigManager']['SetMinimizeToTray'](arg1);
}

export function SetServiceState(arg1) {
  return window['go']['app']['ConfigManager']['SetServiceState'](arg1);
}

export function SetStartMinimized(arg1) {
  return window['go']['app']['ConfigManager']['SetStartMinimized'](arg1);
}

export function SetTrayNotifications(arg1) {
  return window['go']['app']['ConfigManager']['SetTrayNotifications'](arg1);
}

export function ValidateHotkey(arg1) {
  return window['go']['app']['ConfigManager']['ValidateHotkey'](arg1);
}
