// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentHotkey() {
  return window['go']['app']['HotkeyManager']['GetCurrentHotkey']();
}

export function GetHotkeyCount() {
  return window['go']['app']['HotkeyManager']['GetHotkeyCount']();
}

export function GetHotkeyStats() {
  return window['go']['app']['HotkeyManager']['GetHotkeyStats']();
}

export function GetRegisteredHotkeys() {
  return window['go']['app']['HotkeyManager']['GetRegisteredHotkeys']();
}

export function IsHotkeyRegistered(arg1) {
  return window['go']['app']['HotkeyManager']['IsHotkeyRegistered'](arg1);
}

export function IsMessageLoopRunning() {
  return window['go']['app']['HotkeyManager']['IsMessageLoopRunning']();
}

export function OnShutdown(arg1) {
  return window['go']['app']['HotkeyManager']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['HotkeyManager']['OnStartup'](arg1);
}

export function RegisterHotkey(arg1) {
  return window['go']['app']['HotkeyManager']['RegisterHotkey'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['app']['HotkeyManager']['SetHotkey'](arg1);
}

export function UnregisterHotkey(arg1) {
  return window['go']['app']['HotkeyManager']['UnregisterHotkey'](arg1);
}

export function UpdateHotkey(arg1, arg2) {
  return window['go']['app']['HotkeyManager']['UpdateHotkey'](arg1, arg2);
}

export function ValidateHotkey(arg1) {
  return window['go']['app']['HotkeyManager']['ValidateHotkey'](arg1);
}
