// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCurrentHotkey():Promise<string>;

export function GetHotkeyCount():Promise<number>;

export function GetHotkeyStats():Promise<Record<string, any>>;

export function GetRegisteredHotkeys():Promise<Array<string>>;

export function IsHotkeyRegistered(arg1:string):Promise<boolean>;

export function IsMessageLoopRunning():Promise<boolean>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RegisterHotkey(arg1:string):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function UnregisterHotkey(arg1:string):Promise<void>;

export function UpdateHotkey(arg1:string,arg2:string):Promise<void>;

export function ValidateHotkey(arg1:string):Promise<void>;
