// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetServiceStatus(arg1:string):Promise<string>;

export function GetServices():Promise<Array<app.Service>>;

export function RestartService(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
