// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableService(arg1) {
  return window['go']['app']['ServiceManager']['DisableService'](arg1);
}

export function DisableServiceControl() {
  return window['go']['app']['ServiceManager']['DisableServiceControl']();
}

export function EnableService(arg1) {
  return window['go']['app']['ServiceManager']['EnableService'](arg1);
}

export function EnableServiceControl() {
  return window['go']['app']['ServiceManager']['EnableServiceControl']();
}

export function GetElevationStatus() {
  return window['go']['app']['ServiceManager']['GetElevationStatus']();
}

export function GetPrivilegeInfo() {
  return window['go']['app']['ServiceManager']['GetPrivilegeInfo']();
}

export function GetServiceControlState() {
  return window['go']['app']['ServiceManager']['GetServiceControlState']();
}

export function GetServiceStatus(arg1) {
  return window['go']['app']['ServiceManager']['GetServiceStatus'](arg1);
}

export function GetServices() {
  return window['go']['app']['ServiceManager']['GetServices']();
}

export function IsElevated() {
  return window['go']['app']['ServiceManager']['IsElevated']();
}

export function IsServiceControlEnabled() {
  return window['go']['app']['ServiceManager']['IsServiceControlEnabled']();
}

export function OnShutdown(arg1) {
  return window['go']['app']['ServiceManager']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['ServiceManager']['OnStartup'](arg1);
}

export function RequireElevationForOperation() {
  return window['go']['app']['ServiceManager']['RequireElevationForOperation']();
}

export function RestartService(arg1) {
  return window['go']['app']['ServiceManager']['RestartService'](arg1);
}

export function SetServiceControlState(arg1) {
  return window['go']['app']['ServiceManager']['SetServiceControlState'](arg1);
}

export function StartService(arg1) {
  return window['go']['app']['ServiceManager']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['app']['ServiceManager']['StopService'](arg1);
}

export function ToggleServiceControl() {
  return window['go']['app']['ServiceManager']['ToggleServiceControl']();
}
