// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServiceStatus(arg1) {
  return window['go']['app']['ServiceManager']['GetServiceStatus'](arg1);
}

export function GetServices() {
  return window['go']['app']['ServiceManager']['GetServices']();
}

export function OnStartup(arg1) {
  return window['go']['app']['ServiceManager']['OnStartup'](arg1);
}

export function RestartService(arg1) {
  return window['go']['app']['ServiceManager']['RestartService'](arg1);
}

export function StartService(arg1) {
  return window['go']['app']['ServiceManager']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['app']['ServiceManager']['StopService'](arg1);
}
