// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupTray() {
  return window['go']['app']['TrayManager']['CleanupTray']();
}

export function GetServiceStatus() {
  return window['go']['app']['TrayManager']['GetServiceStatus']();
}

export function HandleExit(arg1) {
  return window['go']['app']['TrayManager']['HandleExit'](arg1);
}

export function HandleOpenApp(arg1) {
  return window['go']['app']['TrayManager']['HandleOpenApp'](arg1);
}

export function HandleToggleService(arg1) {
  return window['go']['app']['TrayManager']['HandleToggleService'](arg1);
}

export function InitializeTray() {
  return window['go']['app']['TrayManager']['InitializeTray']();
}

export function IsForceExit() {
  return window['go']['app']['TrayManager']['IsForceExit']();
}

export function IsSystemTraySupported() {
  return window['go']['app']['TrayManager']['IsSystemTraySupported']();
}

export function IsTrayIconVisible() {
  return window['go']['app']['TrayManager']['IsTrayIconVisible']();
}

export function MinimizeToTray() {
  return window['go']['app']['TrayManager']['MinimizeToTray']();
}

export function OnShutdown(arg1) {
  return window['go']['app']['TrayManager']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['app']['TrayManager']['OnStartup'](arg1);
}

export function RefreshContextMenu() {
  return window['go']['app']['TrayManager']['RefreshContextMenu']();
}

export function RestoreFromTray() {
  return window['go']['app']['TrayManager']['RestoreFromTray']();
}

export function UpdateTrayIcon() {
  return window['go']['app']['TrayManager']['UpdateTrayIcon']();
}
