// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {menu} from '../models';
import {context} from '../models';

export function CleanupTray():Promise<void>;

export function GetServiceStatus():Promise<app.ServiceStatus>;

export function HandleExit(arg1:menu.CallbackData):Promise<void>;

export function HandleOpenApp(arg1:menu.CallbackData):Promise<void>;

export function HandleToggleService(arg1:menu.CallbackData):Promise<void>;

export function InitializeTray():Promise<void>;

export function IsSystemTraySupported():Promise<boolean>;

export function IsTrayIconVisible():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RefreshContextMenu():Promise<void>;

export function RestoreFromTray():Promise<void>;

export function UpdateTrayIcon():Promise<void>;
