// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<void>;

export function IsWindows():Promise<boolean>;

export function Minimize():Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function StartDrag():Promise<void>;
